yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index')
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model

from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Слаг адреса', unique=True)
    description = models.TextField('Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='author_posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name='group_posts',
        verbose_name='Группа'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


# Главная страница
def index(request):
    posts = Post.objects.all()[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


# Страница с постами, отфильтрованными по группам
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
    {% block title %} 
    Без названия
    {% endblock %}
    </title>
  </head>
  <body>
    <header>   
      {% include "includes/header.html" %}    
    </header>
    <main>
      {% block content %}
      Без контента
      {% endblock %}  
    </main>      
    <footer class="border-top text-center py-3"> 
      {% include "includes/footer.html" %}  
    </footer>
  </body>

yatube/templates/includes/footer.html
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
<div class="container">
  <a class="navbar-brand" href="{% url 'posts:index' %}">
    {% load static %}
    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <span style="color:red">Ya</span>tube</a>
  </a>
</div>
</nav> 

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}
<div class="container py-5">
  <p>{{ group.description }}</p>
  {% for post in posts %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>      
      <p>{{ post.text }}</p>         
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
Последние обновления на сайте
{% endblock %}

{% block content %}
<div class="container py-5">     
  {% for post in posts %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}">
        все записи группы
        </a> 
      {% endif %}
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>
{% endblock %}